### ISSUE TITLE
Release a new version to the PyPI

### ISSUE THREAD

**Issue by x3ro** [fitzgen/pycco#66]
I just installed pycco using `pip` and was wondering why the background was not staying behind the code when scrolling horizontally, which was [fixed over a year ago](https://github.com/fitzgen/pycco/commit/459f92f4956c793650dd582a68243899b2fc4b1f). It turns out there hasn't been a new version for quite some time :) It'd be great if a new version could be released!

:shipit:

**Comment by pquentin** [comment]
@fitzgen anything we can do to help? Having to install from the GitHub version is not so nice. Thanks!

**Comment by fitzgen** [comment]
I don't maintain this repository anymore, that would be @subsetpark now :)


_Nick_

**Comment by subsetpark** [comment]
@pquentin @x3ro, thanks for the heads up. There is one more bugfix in the pipeline, and then I will be releasing an updated version of Pycco. I appreciate your patience - expect one within a week!

**Comment by pquentin** [comment]
@subsetpark awesome, thanks.

**Comment by subsetpark** [comment]
Hey @pquentin @x3ro, I just merged a bugfix for multiline comments and released a new version, 0.3.1, on PyPI. Enjoy!

**Comment by pquentin** [comment]
@subsetpark Thanks! :100:
